# Docker Compose File for Application Container with Docker bindings
version: '3.1'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always

    ports:
      - "3306:3306"

    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: example
      MYSQL_PASSWORD:example

    volumes:
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/data
        consistency: consistent

volumes:
  postgres-data:
